export enum EntitiesEnum {
    User = "user",
    Customer = "customer",
    Employee = "employee",
    AddressBook = "address_book",
    Product = "product",
    ProductReview = "product_review",
    Cart = "cart",
    Order = "order",
    Wishlist = "wishlist",
    Organization = "organization",
    WeekSchedule = "week_schedule",
    Category = "category",
    Subcategory = "subcategory",
    Token = "token",
    Payment = "payment",
    Image = "image",
    Delivery = "delivery",
    OrderItem = "order_item",
    CartItem = "cart_item",
    WishlistItem = "wishlist_item",
    ProductStock = "product_stock",
    ProductStockSetting = "product_stock_setting",
}
